recruitment/routes/web.php
<?php

use Illuminate\Http\Request;
use App\Person;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
// Routes for the main views
Route::get('update-applicant', function() {
  return view('update-applicant');
})->name('update-applicant');

//Routes for application model
Route::resource('application', 'ApplicationController');

//Routes for person model
Route::get('person/update/{person}', 'PersonController@showUpdate')->name('person-update');
Route::get('person/filtered', 'PersonController@filterResults')->name('person-filtered');
Route::patch('person/{person}/updateOffer', 'PersonController@setOffer')->name('person.setOffer');
Route::patch('person/{person}/setOfferReponse', 'PersonController@setOfferReponse')->name('person.setOfferReponse');
Route::get('photos/{photo}', 'PersonController@showPhoto');
Route::get('cvs/{cv}', 'PersonController@showCV');

Route::resource('person', 'PersonController');



//Routes for interview model
Route::resource('interview', 'InterviewController');


//Routes for authentication
Auth::routes();
Route::get('/home', 'HomeController@index')->name('home');

recruitment/resources/views/navs/nav-top.blade.php
<nav class="navbar navbar-default navbar-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href={{ route('home' )}}>Home</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a href={{ route('person.index' )}}>All Applicants</a></li>
        <li><a href={{ route('interview.index' )}}>Interview Schedule</a></li>

        <li><a href={{ route('application.create') }}>New Applicant</a></li>
      </ul>

      <!-- Right Side Of Navbar -->
      <!-- <ul>
        <form class="nav navbar-nav navbar-form navbar-right">
          <div class="form-group">
            <input type="text" class="form-control" placeholder="Search">
          </div>
          <button type="submit" class="btn btn-default">Submit</button>
        </form>
      </ul> -->
      <ul class="nav navbar-nav navbar-right">
          <!-- Authentication Links -->
          @if (Auth::guest())
              <li><a href="{{ route('login') }}">Login</a></li>
              <li><a href="{{ route('register') }}">Register</a></li>
          @else
              <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                      {{ Auth::user()->name }} <span class="caret"></span>
                  </a>

                  <ul class="dropdown-menu" role="menu">
                      <li>
                          <a href="{{ route('logout') }}"
                              onclick="event.preventDefault();
                                       document.getElementById('logout-form').submit();">
                              Logout
                          </a>

                          <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                              {{ csrf_field() }}
                          </form>
                      </li>
                  </ul>
              </li>
          @endif
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

recruitment/resources/views/navs/sidebar.blade.php
<div class="col-md-2">
  <br><br>
  <div class="panel panel-default hidden-xs" style="height: 100%;">
    <div class="panel-heading dash-panel-head" style="text-align: center">
      <h5>Actions</h5>
    </div>
    <div class="panel-body">
      <ul class="dash-list">
        <li class="dash-list-item">
          Inverviews to schedule
          <span class="badge sidebar-badge">
            {{ App\Http\Controllers\InterviewController::getScheduleCount() }}
            <!-- count the number of most recent interviews for a person where status != pending -->
          </span>
        </li>
        <li class="dash-list-item">
          Interviews to review
          <span class="badge sidebar-badge">
            {{ App\Http\Controllers\InterviewController::getReviewCount() }}
            <!-- fix this route -->
          </span>
        </li>
      </ul>
    </div>
  </div>
</div>