recruitment/routes/web.php
<?php

use Illuminate\Http\Request;
use App\Person;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
// Routes for the main views
Route::get('update-applicant', function() {
  return view('update-applicant');
})->name('update-applicant');

//Routes for application model
Route::resource('application', 'ApplicationController');

//Routes for person model
Route::get('person/update/{person}', 'PersonController@showUpdate')->name('person-update');
Route::get('person/filtered', 'PersonController@filterResults')->name('person-filtered');
Route::patch('person/{person}/updateOffer', 'PersonController@setOffer')->name('person.setOffer');
Route::patch('person/{person}/setOfferReponse', 'PersonController@setOfferReponse')->name('person.setOfferReponse');
Route::get('photos/{photo}', 'PersonController@showPhoto');
Route::get('cvs/{cv}', 'PersonController@showCV');

Route::resource('person', 'PersonController');



//Routes for interview model
Route::resource('interview', 'InterviewController');


//Routes for authentication
Auth::routes();
Route::get('/home', 'HomeController@index')->name('home');

recruitment/app/Person.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Person extends Model
{
  protected $fillable = [
      'name', 'surname', 'birthdate', 'nationality', 'welsh', 'CV', 'email', 'phone', 'lead_type', 'photo'
  ];

  public function application() {
    return $this->hasOne('App\Application');
  }

  public function getUrlAttribute() {
    return route('person.show', $this->id);
  }
}

recruitment/resources/views/current-applicants.blade.php
@extends('layouts.master')
@section('content')

<br>
<h3>All Applicants</h3>

<!-- Multiple Radios -->
<div class="col-md-2">
  <form method="get" action={{ route('person-filtered')}}>
    {{ csrf_field() }}

    <br><br>
    <div class="form-group">
      <label class="form-label">Select:</label>
      <div class="checkbox">
        <label>
          <input type="checkbox" name="status[]" id="status[]" value="In Progress">
          In Progress
        </label>
      </div>
      <div class="checkbox">
        <label>
          <input type="checkbox" name="status[]" id="status[]" value="Rejected">
          Rejected
        </label>
      </div>
      <div class="checkbox ">
        <label>
          <input type="checkbox" name="status[]" id="status[]" value="Hired">
          Hired
        </label>
      </div>
    </div>

    From :
    <input type="date" class="form-control" name="fromDate" id="fromDate" placeholder="dd/mm/YYYY" style="font-size: 0.8rem">
    To:
    <input type="date" class="form-control" name="toDate" id="toDate" placeholder="dd/mm/YYYY" style="font-size: 0.8rem">
    <button type="submit" class="btn btn-dash" style="margin-left:0" name="filter">Filter</button>
  </form>

</div>

<!-- Search for names -->
<div class="col-md-2" style="margin-left:20px;">
  <br>
  <input type="text" id="search" onkeyup="tableSearch()" placeholder="Search for names..">
  <br>
</div>

<!-- Table -->
<div class="col-md-8" style="margin-left:20px;">
  <table class="table table-hover table-responsive" id="peopleTable">
    <thead>
      <tr>
        <td>Name</td>
        <td>Application Status</td>
        <td>Submission Date</td>
        <td>Lead Type</td>
        <td>CV</td>
      </tr>
    </thead>
    <tbody>

      @if (isset($people))
      @foreach($people as $person)
        <tr>
          <td><a href="{{ $person->url }}">{{ $person->name }} {{ $person->surname }}</a></td>
          <td>{{ $person->status }}</td>
          <td>{{ $person->created_at }}</td>
          <td>{{ $person->lead_type }}</td>
          <td><a class="btn btn-default" href="#" role="button">CV</a></td>
        </tr>
      @endforeach
      @endif

    </tbody>
  </table>
</div>

@endsection


@section('scripts')
  <script>
    function tableSearch() {
      // Declare variables
      var input, filter, table, tr, td, i;
      input = document.getElementById("search");
      filter = input.value.toUpperCase();
      table = document.getElementById("peopleTable");
      tr = table.getElementsByTagName("tr");

      // Loop through all table rows, and hide those who don't match the search query
      for (i = 0; i < tr.length; i++) {
        td = tr[i].getElementsByTagName("td")[0];
        if (td) {
          if (td.innerHTML.toUpperCase().indexOf(filter) > -1) {
            tr[i].style.display = "";
          } else {
            tr[i].style.display = "none";
          }
        }
      }
    }
  </script>

  @endsection

recruitment/resources/views/current-cohort.blade.php
@extends('layouts.master')

@section('content')
  <h1>Current Cohort</h1>
  <br>

  <div class="col-md-4">
    <div class="panel">
      <div class="panel panel-body" style="text-align: center">
        <h2>Team 1</h2>
        <br>
        <ul class="person-list">
          <li class="person-list-item"><i class="glyphicon glyphicon-user"></i> Person 1</li>
          <li class="person-list-item"><i class="glyphicon glyphicon-user"></i> Person 2</li>
          <li class="person-list-item"><i class="glyphicon glyphicon-user"></i> Person 3</li>
          <li class="person-list-item"><i class="glyphicon glyphicon-user"></i> Person 4</li>
        </ul>
        <br>
      </div>
    </div>
  </div>

  <div class="col-md-4">
    <div class="panel">
      <div class="panel panel-body" style="text-align: center">
        <h2>Team 2</h2>
        <br>
        <ul class="person-list">
          <li class="person-list-item"><i class="glyphicon glyphicon-user"></i> Person 1</li>
          <li class="person-list-item"><i class="glyphicon glyphicon-user"></i> Person 2</li>
          <li class="person-list-item"><i class="glyphicon glyphicon-user"></i> Person 3</li>
          <li class="person-list-item"><i class="glyphicon glyphicon-user"></i> Person 4</li>
        </ul>
        <br>
      </div>
    </div>
  </div>

  <div class="col-md-4">
    <div class="panel">
      <div class="panel panel-body" style="text-align: center">
        <h2>Team 3</h2>
        <br>
        <ul class="person-list">
          <li class="person-list-item"><i class="glyphicon glyphicon-user"></i> Person 1</li>
          <li class="person-list-item"><i class="glyphicon glyphicon-user"></i> Person 2</li>
          <li class="person-list-item"><i class="glyphicon glyphicon-user"></i> Person 3</li>
          <li class="person-list-item"><i class="glyphicon glyphicon-user"></i> Person 4</li>
        </ul>
        <br>
      </div>
    </div>
  </div>
@endsection

recruitment/resources/views/dashboard.blade.php
@extends('layouts.dashboard')

@section('content')
<body style="background-color: #80cbc4">
  <div class="container-fluid">
    <br>
    <br>
    <br>
    <div class="dash-text-primary" >
      <h1 class="dash-text-primary">Welcome</h1>
      <p><a class="btn btn-dash btn-lg" href="login" role="button">Sign In</a></p>
    </div>
  </div>
</body>

@endsection

recruitment/resources/views/home.blade.php
@extends('layouts.dashboard')


@section('content')
<body style="background-color: #80cbc4">
  <div class="container">
    <br><br><br><br>
    @if (session('status'))
        <div class="alert alert-success">
            {{ session('status') }}
        </div>
    @endif


  </div>

  @if (Auth::guest())
      <p><a class="btn btn-dash btn-lg" href="login" role="button">Log In</a></p>
  @else
      <div class="dash-text-primary" >
        <h1 class="dash-text-primary">Welcome</h1>

        <form id="logout-form" action="{{ route('login') }}"method="POST">
            {{ csrf_field() }}

            <p><a class="btn btn-dash btn-lg" href="{{ route('login') }}"
                onclick="event.preventDefault();
                         document.getElementById('logout-form').submit();" role="button">Log Out</a></p>
        </form>
      </div>
  @endif

</body>
@endsection

recruitment/resources/views/interview-schedule.blade.php
@extends('layouts.master')

@section('content')

<!-- Change state of interview to pending if it is in the past -->
@if (isset($interviews))
  @foreach($interviews as $interview)
    @if ($interview->date < Carbon\Carbon::now() && $interview->state == 'Scheduled')
      {{ App\Http\Controllers\InterviewController::setPending($interview) }}
    @endif
  @endforeach
@endif

  <div class="col-md-7 ">
    <h3>Upcoming Interviews</h3>
    <table class="table table-hover table-responsive" style="width:100%">
      <thead>
        <tr>
          <td>Date</td>
          <td>Time</td>
          <td>Lead Interviewer</td>
          <td>Applicant</td>
          <td>  </td>
        </tr>
      </thead>
      <tbody>

        @if (isset($interviews))
          @foreach($interviews as $interview)
            @if ($interview->date >= Carbon\Carbon::now())
              <tr>
                <td><i class="glyphicon glyphicon-calendar"></i> {{ $interview->date }}</td>
                <td><i class="glyphicon glyphicon-time"></i> {{ $interview->time }}</td>
                <td> {{ $interview->lead_interviewer }}</td>
                <td><a href="{{ $interview->application->person->url }}">
                  {{ $interview->application->person->name }} {{ $interview->application->person->surname }}
                </a></td>
                <td>
                  <form style="vertical-align:top" method="post" action={{ route('interview.destroy', $interview->id) }}>
                    {{ csrf_field() }}
                    {{ method_field('DELETE') }}
                    <button class="btn btn-default btn-xs" type="submit"><span class="glyphicon glyphicon-trash" style="color:white" ></span></button>
                  </form>
                </td>
              </tr>
            @endif
          @endforeach
        @endif

      </tbody>
    </table>
    <br><br>

    <h3>Interviews to Review</h3>
    <table class="table table-hover table-responsive" style="width:100%">
      <thead>
        <tr>
          <td>Date</td>
          <td>Time</td>
          <td>Lead Interviewer</td>
          <td>Applicant</td>
          <td>  </td>
        </tr>
      </thead>
      <tbody>

        @if (isset($interviews))
          @foreach($interviews as $interview)
            @if (($interview->date < Carbon\Carbon::now()) && ($interview->state == 'Pending'))
              <tr>
                <td><i class="glyphicon glyphicon-calendar"></i> {{ $interview->date }}</td>
                <td><i class="glyphicon glyphicon-time"></i> {{ $interview->time }}</td>
                <td> {{ $interview->lead_interviewer }}</td>
                <td><a href="{{ $interview->application->person->url }}">
                  {{ $interview->application->person->name }} {{ $interview->application->person->surname }}
                </a></td>
                <td>
                  <form style="vertical-align:top" method="post" action={{ route('interview.destroy', $interview->id) }}>
                    {{ csrf_field() }}
                    {{ method_field('DELETE') }}
                    <button class="btn btn-default btn-xs" type="submit"><span class="glyphicon glyphicon-trash" style="color:white" ></span></button>
                  </form>
                </td>
              </tr>
            @endif
          @endforeach
        @endif

      </tbody>
    </table>
  </div>

  <div class="col-md-3 col-md-offset-1">
    <br><br>
    <div class="panel panel-default" >
      <div class="panel-heading interview-panel-head" style="text-align: center">
        <h5>Schedule Interview</h5>
      </div>
      <div class="panel-body">

        <form method="post" action="/interview">
          {{ csrf_field() }}

          <div class="form-group">
            <label class="sr-only" for="name">Name</label>
            <input type="text" class="form-control" id="name" placeholder="Name" name="name">
            <label class="sr-only" for="surname">Surname</label>
            <input type="text" class="form-control" id="surname" placeholder="Surname" name="surname">
            <br>
            <label class="form-label" for="email">Applicant Email</label>
            <input type="email" class="form-control" id="email" placeholder="Email" name="email">
            <label class="form-label" for="date">Date  </label>
            <input type="date" class="form-control" id="date" placeholder="dd/mm/YYYY" name="date">
            <label class="form-label" for="time">Time  </label>
            <input type="time" class="form-control" id="interviewTime" placeholder="" name="time">
            <label class="form-label" for="type">Type  </label>
            <input type="text" class="form-control" id="type" placeholder="e.g Technical" name="type">
            <label class="form-label" for="lead_interviewer">Lead Interviewer  </label>
            <input type="text" class="form-control" id="lead_interviewer" placeholder="Full name" name="lead_interviewer">
            <br>
          </div>
          <div class="form-group" style="text-align:center" >
            <button type="submit" class="btn btn-dash" name="save">Save</button>
          </div>
        </form>

      </div>
    </div>
  </div>

  <!-- Calendar  -->
  <!-- <div class="col-md-8">
    <div class="responsive-iframe-container big-container hidden-xs">
      <iframe src="https://calendar.google.com/calendar/embed?showTitle=0&amp;showPrint=0&amp;showCalendars=0&amp;height=900&amp;wkst=2&amp;bgcolor=%23FFFFFF&amp;src=en.uk%23holiday%40group.v.calendar.google.com&amp;color=%2329527A&amp;ctz=Europe%2FLondon"
        style="border-width:0" width="1200" height="900" frameborder="0" scrolling="no">
      </iframe>
    </div>
    <div class="responsive-iframe-container small-container hidden-lg hidden-md">
      <iframe src="https://calendar.google.com/calendar/embed?showTitle=0&amp;showPrint=0&amp;showTz=0&amp;mode=AGENDA&amp;height=600&amp;wkst=1&amp;bgcolor=%23FFFFFF&amp;src=en.uk%23holiday%40group.v.calendar.google.com&amp;color=%2329527A&amp;ctz=Europe%2FLondon"
        style="border-width:0" width="100%" height="600" frameborder="0" scrolling="no">
      </iframe>
    </div>
  </div> -->
@endsection

recruitment/resources/views/master.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Recruitment App</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <link href="https://fonts.googleapis.com/css?family=Comfortaa" rel="stylesheet">
  <link rel="stylesheet" href="/css/mdb.css">
  <link rel="stylesheet" href="/css/custom-style.css">

</head>
<body>



<script> new WOW().init();</script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.nicescroll/3.6.8-fix/jquery.nicescroll.min.js"></script>

</body>
</html>

recruitment/resources/views/person.blade.php
@extends('layouts.master')
@section('content')

  <div class="col-md-4">
    <br><br>
    <div class="panel">
      <div class="panel panel-body" style="text-align: center">
        <div class="circle-avatar" style="background-image:url('/{{ $person->photo }}')"></div>
        <h2>{{ $person->name}} {{ $person->surname }}</h2>


        @if ($person->status == 'Rejected')
          <h5><span class="label label-danger">Rejected</span></h5>
        @endif

        <br>
        <ul class="person-list">
          <li class="person-list-item"><i class="glyphicon glyphicon-flash"></i> Status: {{ $person->status }}</li>
          <li class="person-list-item"><i class="glyphicon glyphicon-envelope"></i> {{ $person->email }}</li>
          <li class="person-list-item"><i class="glyphicon glyphicon-earphone"></i>  {{ $person->phone }}</li>
          @if ($person->CV)
          <li>
            <a class="btn btn-default" href="/{{ $person->CV }}" target="_blank">CV</a>
          </li>
          @else
          <li>
            <a class="btn btn-default disabled" disabled="disabled" href="/{{ $person->CV }}" target="_blank">CV</a>
          </li>
          @endif
          <li>
            <form  method="post" action={{ route('person.destroy', $person->id) }}>
              {{ csrf_field() }}
              {{ method_field('DELETE') }}
              <button class="btn btn-dash" type="submit">Delete Profile</button>
            </form>
          </li>
        </ul>
        <br>
      </div>
    </div>
  </div>

  <div class="col-md-8">
    <br><br>
    <div class="row bs-wizard hidden-xs" style="border-bottom:0;">

      @if ($person->status != 'Rejected')
        <div class="col-xs-3 bs-wizard-step complete">
      @else
      <div class="col-xs-3 bs-wizard-step disabled">
      @endif
        <div class="text-center bs-wizard-stepnum">Successful Submission</div>
        <div class="progress"><div class="progress-bar"></div></div>
        <i class="bs-wizard-dot"></i>
      </div>

      @if ($person->application->interview()->count() > 1 && $person->status == 'In Progress'
        || $person->status == 'Offer Made' || $person->status == 'Hired'
        || $person->status == 'Offer Rejected')
        <div class="col-xs-3 bs-wizard-step complete">
      @else
      <div class="col-xs-3 bs-wizard-step disabled">
      @endif
        <div class="text-center bs-wizard-stepnum">Interviews In Progress</div>
        <div class="progress"><div class="progress-bar"></div></div>
        <i class="bs-wizard-dot"></i>
      </div>

      @if ($person->application->offer == 1)
        <div class="col-xs-3 bs-wizard-step complete">
      @else
      <div class="col-xs-3 bs-wizard-step disabled">
      @endif
        <div class="text-center bs-wizard-stepnum">Offer Made</div>
        <div class="progress"><div class="progress-bar"></div></div>
        <i class="bs-wizard-dot"></i>
      </div>

      @if ($person->status == 'Hired')
        <div class="col-xs-3 bs-wizard-step complete">
      @else
      <div class="col-xs-3 bs-wizard-step disabled">
      @endif
        <div class="text-center bs-wizard-stepnum">Hired</div>
        <div class="progress"><div class="progress-bar"></div></div>
        <i class="bs-wizard-dot"></i>
      </div>
    </div>

    <div class="notice" style="text-align: center">
      <br><br>
      <!-- If there is an interview in the future, write the date and time here -->
      @if ($person->application->interview->last()->date > Carbon\Carbon::now()
        && $person->application->interview->last()->state == 'Scheduled'
        || $person->application->interview[0]->state == 'Pending'
        && $person->application->offer != 1)
        <h5><span class="label label-action">
          Interview with {{$person->application->interview->last()->lead_interviewer}}
          on {{$person->application->interview->last()->date}}
          at {{$person->application->interview->last()->time}}
        </span></h5>
        <br><br>
      @endif

      @if ($person->status != 'Rejected' && $person->application->interview->last()->state == 'Unscheduled'
      || $person->application->interview->last()->state == 'Passed'
      && $person->application->offer != 1)
      <button class="btn btn-default" type="submit">
        <a style="color:white" href={{ route('interview.index' )}}>Schedule Interview</a>
      </button>
      @else
        <a class="btn btn-default disabled" disabled = "disabled" style="color:white" href={{ route('interview.index' )}}>Schedule Interview</a>
      @endif

      @if ($person->application->interview->last()->state == 'Pending' && $person->application->offer != 1)
        <button class="btn btn-default" type="submit" data-toggle="modal" data-target="#update-progress">Update Progress</button>
      @else
        <button class="btn btn-default disabled" disabled="disabled" type="submit" data-toggle="modal" data-target="#update-progress">Update Progress</button>
      @endif

      @if ($person->application->interview->last()->state == 'Passed' && $person->application->offer != 1)
      <button class="btn btn-default" type="submit" data-toggle="modal" data-target="#offer-made">
        Offer Made
      </button>
      @else
        <button class="btn btn-default disabled" disabled="disabled" type="submit" data-toggle="modal" data-target="#offer-made">
          Offer Made
        </button>
      @endif

      @if ($person->application->offer == 1 && $person->status != 'Hired' && $person->status != 'Offer Rejected')
      <button class="btn btn-default" type="submit" data-toggle="modal" data-target="#offer-accepted">
        Offer Accepted
      </button>
      @else
        <button class="btn btn-default disabled" disabled="disabled" type="submit" data-toggle="modal" data-target="#offer-accepted">
          Offer Accepted
        </button>
      @endif

    </div>
    <br><br><br><br>
  </div>

  <div class="col-md-4 col-md-offset-1 ">
    <h4>Full Details</h4>
    <table class="table table-responsive">
      <tbody>
        <tr>
          <td>Name</td>
          <td>{{ $person->name}} {{$person->surname }}</td>
        </tr>
        <tr>
          <td>Lead Type</td>
          <td>{{ $person->lead_type }}</td>
        </tr>
        <tr>
          <td>Status</td>
          <td>{{ $person->status }}</td>
        </tr>
        <tr>
          <td>Date of Birth</td>
          <td>{{ $person->birthdate }}</td>
        </tr>
        <tr>
          <td>Nationality</td>
          <td>{{ $person->nationality }}</td>
        </tr>
        <tr>
          <td>Welsh?</td>
          <td>{{ $person->welsh?'Yes':'No' }}</td>
        </tr>

      </tbody>
    </table>

    <button class="btn btn-default" type="submit">
      <a style="color:white" href={{ route('person-update', $person) }}>Update Details</a>
    </button>

   </div>


  <!-- Modals -->
<div id="update-progress" class="modal fade" role="dialog">
  <div class="modal-dialog">
    <!-- Modal content-->
    <div class="modal-content" style="width: 300px">
      <div class="modal-body" style="text-align:center">
        <form method="post" action={{ route('interview.update', $interview) }}>
          {{ method_field('PATCH') }}
          {{ csrf_field() }}

          <button class="btn btn-default" type="submit" name="state" value="Passed">Progress to Next Stage</button>
          <br>
          <button class="btn btn-dash" type="submit" name="state" value="Failed">Reject</button>
          <br>
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <br>
        </form>
      </div>
    </div>
  </div>
</div>

<div id="offer-made" class="modal fade" role="dialog">
  <div class="modal-dialog">
    <!-- Modal content-->
    <div class="modal-content" style="width: 300px">
      <div class="modal-body" style="text-align:center">
        <form method="post" action="{{ route('person.setOffer', $person->id) }}">
          {{ method_field('PATCH') }}
          {{ csrf_field() }}

          <p>Has an offer been made to {{ $person->name }}?</p>
          <button class="btn btn-default" type="submit" name="status" value="Offer Made">Yes</button>
          <button class="btn btn-dash" data-dismiss="modal">No</button>
          <br>
        </form>
      </div>
    </div>
  </div>
</div>

<div id="offer-accepted" class="modal fade" role="dialog">
  <div class="modal-dialog">
    <!-- Modal content-->
    <div class="modal-content" style="width: 300px">
      <div class="modal-body" style="text-align:center">
        <form method="post" action="{{ route('person.setOfferReponse', $person->id) }}">
          {{ method_field('PATCH') }}
          {{ csrf_field() }}

          <p>Has the offer been accepted by {{ $person->name }}?</p>
          <button class="btn btn-default" type="submit" name="status" value="Hired">Yes</button>
          <button class="btn btn-dash" type="submit" name="status" value="Offer Rejected">No</button>
          <br>
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <br>
        </form>
      </div>
    </div>
  </div>
</div>

@endsection

recruitment/resources/views/update-applicant.blade.php
@extends('layouts.master')

@section('content')

<div class="col-md-10">
  <div class="panel panel-default">
    <div class="panel panel-body form">
      <h3>Update {{ $person->name }}'s Details</h3>
      <br>

      @if ($errors->any())

        <ul>
          @foreach ($errors->all() as $error)
          <div class="alert alert-danger">
            <li>{{ $error }}</li>
          </div>
          @endforeach
        </ul>

      @endif

      <form method="post" action="{{ route('person.update', $person->id) }}">
        {{ method_field('PATCH') }}
        {{ csrf_field() }}

        <div class="form-group form-inline">
          <label class="sr-only" for="name">name</label>
          <input type="text" class="form-control" id="name" placeholder={{ $person->name }} name="name">
          <label class="sr-only" for="surname">surname</label>
          <input type="text" class="form-control" id="surname" placeholder={{ $person->surname }} name="surname">
        </div>

        <br>

        <div class="form-group">
          <label class="form-label" for="birthdate">Date of Birth</label>
          <input type="date" class="form-control" id="birthdate" placeholder={{ $person->birthdate }} name="birthdate">
        </div>

        <div class="form-group">
          <label class="form-label" for="nationality">Nationality</label>
          <input type="text" class="form-control" id="nationality" placeholder={{ $person->nationality }} name="nationality">
        </div>

        <div class="form-group">
          <label class="form-label" for="email">Applicant Email</label>
          <input type="email" class="form-control" id="email" placeholder={{ $person->email }} name="email">
        </div>

        <div class="form-group">
          <label class="form-label" for="phone">Applicant Phone Number</label>
          <input type="text" class="form-control" id="phone" placeholder={{ $person->phone }} name="phone">
        </div>

        <div class="form-group">
          <label class="form-label" for="applicationSource">Application Source</label>
          <input type="text" class="form-control" id="applicationSource" placeholder={{ $person->application->source }} name="source">
        </div>

        <div class="form-group">
          <label class="form-label" for="lead_type">Lead Type</label>
          <input type="text" class="form-control" id="lead_type" placeholder={{ $person->lead_type }} name="lead_type">
        </div>
        <br>

        <div class="form-group">
          <label class="form-label" for="CV">Upload CV</label>
          <input type="file" id="CV" name="cv">
        </div>
        <br>

        <div class="form-group">
          <label class="form-label" for="photo">Upload Photo</label>
          <input type="file" id="photo" name="photo">
        </div>
        <br>

        <div class="form-group">
          <label class="form-label" class="control-radio" for="visa">VISA?</label>
          <div class="radio">
            <label class="radio">
              <input type="radio" id="optionsRadios1" value="1" name="visa">
              Yes
            </label>
          </div>
          <div class="radio">
            <label class="radio">
              <input type="radio" id="optionsRadios2" value="0" name="visa">
              No
            </label>
          </div>
        </div>
        <br>

        <div class="form-group">
          <label class="form-label" for="good_candidate">Good Candidate?</label>
          <div class="radio">
            <label>
              <input type="radio" id="optionsRadios1" value="1" name="good_candidate">
              Yes
            </label>
          </div>
          <div class="radio">
            <label>
              <input type="radio" id="optionsRadios2" value="0" name="good_candidate">
              No
            </label>
          </div>
        </div>
        <br>

        <div class="form-group">
          <label class="form-label" for="welsh">Welsh?</label>
          <div class="radio">
            <label>
              <input type="radio" id="optionsRadios1" value="1" name="welsh">
              Yes
            </label>
          </div>
          <div class="radio">
            <label>
              <input type="radio" id="optionsRadios2" value="0" name="welsh">
              No
            </label>
          </div>
        </div>
        <button type="submit" class="btn btn-default" name="save">Save</button>
      </form>
    </div>
    </div>
  </div>

@endsection